### ISSUE TITLE
Isn't compatible with iourt43 parser

### ISSUE THREAD

**Issue by phantasyy** [danielepantaleone/b3-plugin-jumper#2]
170511 18:18:42 BOT      u'Loading configuration file /home/urt/sr8server/b3_master/b3/conf/plugin_jumper.ini for plugin jumper'
170511 18:18:42 BOT      u'Loading configuration file /home/urt/sr8server/b3_master/b3/extplugins/conf/plugin_callvote.ini for plugin callvote'
170511 18:18:42 DEBUG    'Plugin location has unmet dependency : geolocation : trying to load plugin geolocation...'
170511 18:18:42 DEBUG    'Looking for plugin geolocation module and configuration file...'
170511 18:18:42 DEBUG    'No configuration file specified for plugin geolocation: is not required either'
170511 18:18:42 DEBUG    'Plugin location dependency satisfied: geolocation'
170511 18:18:42 ERROR    'Could not load plugin jumper'
Traceback (most recent call last):
  File "/home/urt/sr8server/b3_master/b3/parser.py", line 935, in loadPlugins
    plugin_list += _get_plugin_data(plugin_data)
  File "/home/urt/sr8server/b3_master/b3/parser.py", line 894, in _get_plugin_data
    p_data.name, self.gameName, ', '.join(p_data.clazz.requiresParsers)))
MissingRequirement: 'plugin jumper is not compatible with iourt43 parser : supported games are : iourt42'
170511 18:18:42 ERROR    'Could not load plugin callvote'
Traceback (most recent call last):
  File "/home/urt/sr8server/b3_master/b3/parser.py", line 935, in loadPlugins
    plugin_list += _get_plugin_data(plugin_data)
  File "/home/urt/sr8server/b3_master/b3/parser.py", line 894, in _get_plugin_data
    p_data.name, self.gameName, ', '.join(p_data.clazz.requiresParsers)))
MissingRequirement: 'plugin callvote is not compatible with iourt43 parser : supported games are : iourt42'

**Comment by phantasyy** [comment]
I might add that callvote works without problems but supported games are iourt42.

**Comment by danielepantaleone** [comment]
I'll provide a fix as soon as possible

Inviato da iPhone

**Comment by danielepantaleone** [comment]
You can get both the `callvote` and the `jumper` plugin from [the official B3 repository](https://github.com/BigBrotherBot/big-brother-bot).
They both support Urban Terror 4.3 now.
