### ISSUE TITLE
Can't be loaded

### ISSUE THREAD

**Issue by phantasyy** [danielepantaleone/b3-plugin-jumper#3]
170519 18:27:52 ERROR    'Could not load plugin jumper'
Traceback (most recent call last):
  File "/home/urt/sr8server/b3_master/b3/parser.py", line 859, in loadPlugins
    mod = self.pluginImport(p['name'], p['path'])
  File "/home/urt/sr8server/b3_master/b3/parser.py", line 1072, in pluginImport
    return imp.load_module(name, fp, pathname, description)
  File "/home/urt/sr8server/b3_master/b3/plugins/jumper/__init__.py", line 1093, in <module>
    cmd.sayLoudOrPM(client, '^7map rotation: %s' % ', '.join(maplist))
NameError: name 'cmd' is not defined

**Comment by danielepantaleone** [comment]
Please try to use the version provided with B3 1.10. If the issue persists open a ticket on the B3 official repository.

**Comment by phantasyy** [comment]
I currently am using version 1.10 ( dev )

**Comment by danielepantaleone** [comment]
Can you try with the latest version from [here](https://github.com/BigBrotherBot/big-brother-bot)? Also does this error appears when loading the plugin or when executing a command? Looks like the plugin syntax got messed up somehow in the version you are using. I just tested the plugin from B3 repo and it's working as expected.

**Comment by phantasyy** [comment]
While attempting to load it gives the error. I'll try a new version of the b3 and get back to you with a response if it worked or not.

**Comment by phantasyy** [comment]
Already had the newest b3 version but didn't work.
