### ISSUE TITLE
Error making bot crash

### ISSUE THREAD

**Issue by phantasyy** [danielepantaleone/b3-plugin-jumper#4]
Came across this error when trying to start your plugin
https://hastebin.com/itecafoded.rb

I was able to start the plugin by adding a # to line 1093 where the error occurred but I don't think a cheap fix like that should be acceptable cause it still takes away a function from the plugin?

**Comment by phantasyy** [comment]
Got it working after I added 8 spaces. This is how it was

https://hastebin.com/sequmureko.cs

and this is what I did to made it work, in other words you can close this :-)
https://hastebin.com/puwixasuba.cs

**Comment by danielepantaleone** [comment]
Ah sorry, I totally forgot about this. I believe the version bundled with B3 1.10 is fixed though
